
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.orgname }}-cli-claim0
  labels:
    io.kmpose.service: {{ .Values.orgname }}-cli-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: {{ .Values.orgname }}-cli-claim1
  name: {{ .Values.orgname }}-cli-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: {{ .Values.orgname }}-cli
  name: {{ .Values.orgname }}-cli
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
